# -*- coding: utf-8 -*-
"""demo-qwen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLqFjt-QFLPUKNbwKk7N78WB7QmEkvMl
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

!pip install -q --upgrade \
  "transformers>=4.45.0,<4.47" \
  "accelerate==0.34.2" \
  "huggingface_hub>=0.28.1" \
  "tiktoken>=0.7.0" \
  "einops>=0.7.0" \
  "scikit-learn>=1.6.1"

!pip install thefuzz
!pip install -U bitsandbytes
!pip install outlines jsonformer guidance
!pip install outlines jsonformer

from huggingface_hub import snapshot_download
from pathlib import Path

BASE_REPO = "Qwen/Qwen2.5-0.5B-Instruct"   # repo công khai
BASE_DIR  = "/kaggle/working/models/qwen25-05b-instruct"

Path(BASE_DIR).mkdir(parents=True, exist_ok=True)
BASE_MODEL_LOCAL = snapshot_download(
    repo_id=BASE_REPO,
    local_dir=BASE_DIR,
    local_dir_use_symlinks=False
)
print("BASE_MODEL_LOCAL =", BASE_MODEL_LOCAL)

# === Cell 1: Setup + Helpers + Policy (compact & safe) — in-memory, no file IO ===
import os, re, json, time, unicodedata, difflib
from pathlib import Path
from typing import Optional, List, Dict, Any, Tuple

import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from transformers.generation.logits_process import LogitsProcessorList
from transformers.generation.stopping_criteria import StoppingCriteria, StoppingCriteriaList
from peft import PeftModel
from jsonschema import validate, Draft202012Validator  # Draft 2020-12

# ---------- Runtime env ----------
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("HF_HUB_DISABLE_TELEMETRY", "1")

# ---------------- Default params ----------------
BASE_MODEL  = "Qwen/Qwen2.5-0.5B-Instruct"
CKPT_DIR    = Path("/kaggle/input/checkpoint-250")
POLICY_PATH = Path("/kaggle/input/policy-gen/policy_machine_compact.md")

PRINT_FIRST = 4
RAW_TAIL_CHARS = 600
MAX_NEW_TOKENS = 160
USE_OUTLINE = True
DETERMINISTIC = True

# ==== optional NER backends (English + Vietnamese) ====
try:
    import spacy
    try:
        _SPACY_EN = spacy.load("en_core_web_sm")
    except Exception:
        _SPACY_EN = None
except Exception:
    _SPACY_EN = None

try:
    from underthesea import ner as vn_ner
except Exception:
    vn_ner = None

# ---------------- Canonicalization ----------------
VN_LOC_ASCII = ["Ho Chi Minh", "Ha Noi", "Da Nang"]  # danh sách hợp lệ

# Map đồng nghĩa → giá trị CHUẨN ASCII đúng với enum
LOC_SYNONYMS = {
    # Hồ Chí Minh
    "hcm": "Ho Chi Minh", "sg": "Ho Chi Minh", "saigon": "Ho Chi Minh",
    "ho chi minh": "Ho Chi Minh", "hồ chí minh": "Ho Chi Minh",
    "ho chi minh city": "Ho Chi Minh", "hochiminh": "Ho Chi Minh", "hochiminh city": "Ho Chi Minh",
    "hcm city": "Ho Chi Minh", "hcmc": "Ho Chi Minh", "sai gon": "Ho Chi Minh", "sai gon city": "Ho Chi Minh",
    # Hà Nội
    "hn": "Ha Noi", "hanoi": "Ha Noi", "ha noi": "Ha Noi", "hà nội": "Ha Noi", "hanoi city": "Ha Noi",
    # Đà Nẵng
    "dn": "Da Nang", "danang": "Da Nang", "da nang": "Da Nang", "đà nẵng": "Da Nang", "da nang city": "Da Nang"
}

ALIAS_TO_CANON = {
    # stock
    "check_inventory": "check_stock",
    "check_inventory_tool": "check_stock",
    "check_stock_tool": "check_stock",
    # price
    "check_price_tool": "check_price",
    # spec
    "spec": "check_spec",
    "spec_tool": "check_spec",
    "spec_lookup_tool": "check_spec",
    "specs_lookup_tool": "check_spec",
    "lookup_spec": "check_spec",
    # policy/warranty
    "warranty_lookup": "policy_look_up_tool",
    "warranty_lookup_tool": "policy_look_up_tool",
    "policy_lookup": "policy_look_up_tool",
    "policy_lookup_tool": "policy_look_up_tool",
    "check_warranty": "policy_look_up_tool",
    "check_warranty_policy": "policy_look_up_tool",
    # reviews
    "get_reviews": "get_product_reviews",
    "get_product_review": "get_product_reviews",
    # recommend
    "recommend": "recommend_product",
    "recommendation_tool": "recommend_product",
    # compare
    "compare": "compare_all",
    "compare_products_tool": "compare_all",
    "vs": "compare_all",
    "versus": "compare_all",
}
ALLOWED_TOOLS = [
    "check_stock","check_price","policy_look_up_tool",
    "check_spec","get_product_reviews","recommend_product","compare_all",
]
TOOL_PRIORITY = [
    "check_stock","check_price","policy_look_up_tool","check_spec","get_product_reviews","recommend_product","compare_all"
]

# ---------------- Intent keywords ----------------
INTENT_KEYWORDS = {
    "stock": {"stock","inventory","còn hàng","availability","mua được không","mua duoc khong","today"},
    "price": {"price","giá","gia","bao nhieu","how much","cost"},
    "policy": {"warranty","bảo hành","bao hanh","policy"},
    "spec": {"spec","specs","specification","specifications","thông số","thong so","thông số kỹ thuật","thong so ky thuat","pin","màn hình","evaluate","đánh giá","battery","screen","chip","cpu","gpu","ram","sim","camera","bluetooth","Loudspeaker","display","weight","network","selfie"},
    "reviews": {"review","reviews","đánh giá","danh gia","rating","ratings","feedback","nhận xét","nhan xet","điểm đánh giá","điểm số","customers","say"},
    "recommend": {"recommend","gợi ý","goi y","nên mua gì","nen mua gi","alternative","similar","thay vì","thay vi","suggest","other"},
    "compare": {"compare","so sánh","so sanh","vs","versus"},
}

# ==== alias viết tắt dòng điện thoại trước khi trích sản phẩm ====
_ALIAS_PATTERNS = [
    # iPhone
    (r"\bip\s?(\d{2})\s?(pm|pro\s?max)\b", r"iphone \1 pro max"),
    (r"\bip\s?(\d{2})\s?(pro|p)\b",        r"iphone \1 pro"),
    (r"\bip\s?(\d{2})\b",                  r"iphone \1"),
    # Samsung Galaxy
    (r"\bs(\d{2})\s?u\b",                  r"galaxy s\1 ultra"),
    (r"\bs(\d{2})\s?fe\b",                 r"galaxy s\1 fe"),
    (r"\ba(\d{2})\s?5g\b",                 r"galaxy a\1 5g"),
    (r"\ba(\d{2})\b",                      r"galaxy a\1"),
    # Google Pixel
    (r"\bp(\d)\s?p\b",                     r"pixel \1 pro"),
    (r"\bp(\d)\b",                         r"pixel \1"),
    # OnePlus
    (r"\b1\+(\d{1,2})\b",                  r"oneplus \1"),
    (r"\bop\s?(\d{1,2})\b",                r"oneplus \1"),
]
def _expand_phone_aliases(q: str) -> str:
    s = _basic_norm(q)
    for pat, rep in _ALIAS_PATTERNS:
        s = re.sub(pat, rep, s)
    return s

# -------- Reviews robust patterns --------
REVIEW_PATTERNS = [
    r"\b\d(\.\d)?\s*/\s*5\b",
    r"\b\d(\.\d)?\s*/\s*10\b",
    r"\b\d(\.\d)?\s*sao\b",
    r"[⭐★]{1,5}",
    r"\b(score|điểm|rating)\s*:?\s*\d(\.\d)?\b",
]

def has_reviews_intent(text: str) -> bool:
    if not isinstance(text, str) or not text.strip():
        return False
    qn = unicodedata.normalize("NFD", text)
    qn = "".join(ch for ch in qn if not unicodedata.combining(ch))
    qn = re.sub(r"[^a-zA-Z0-9\s\-\+_/\.⭐★]", " ", qn).lower().strip()
    for kw in INTENT_KEYWORDS["reviews"]:
        if kw in qn:
            return True
    for pat in REVIEW_PATTERNS:
        if re.search(pat, qn, flags=re.I):
            return True
    return False

# ---------------- JSON Schema ----------------
JSON_SCHEMA: Dict[str, Any] = {
  "type":"object",
  "properties":{
    "reasoning":{"type":["string","null"], "maxLength":96},
    "location":{"enum":["Ho Chi Minh","Ha Noi","Da Nang", None]},
    "tool_sequence":{
      "type":"array",
      "items":{
        "type":"object",
        "properties":{
          "tool":{"enum": ALLOWED_TOOLS},
          "args":{
            "oneOf":[
              {
                "type":"object",
                "properties":{
                  "product":{"type":"string"},
                  "total_product":{"type":"string", "pattern":"^[1-9]\\d*$"}
                },
                "required":["product","total_product"],
                "additionalProperties": False
              },
              {
                "type":"object",
                "properties":{
                  "products":{"type":"array","items":{"type":"string"},"minItems":2},
                  "total_product":{"type":"string","pattern":"^[1-9]\\d*$"}
                },
                "required":["products","total_product"],
                "additionalProperties": False
              }
            ]
          }
        },
        "required":["tool","args"],
        "additionalProperties": False
      }
    }
  },
  "required":["reasoning","tool_sequence"],
  "additionalProperties": False
}

def validate_or_raise(obj: Dict[str, Any]) -> None:
    Draft202012Validator.check_schema(JSON_SCHEMA)
    validate(instance=obj, schema=JSON_SCHEMA)

# ---------------- Basic text utils ----------------
def _strip_accents(s: str) -> str:
    if not isinstance(s, str):
        return ""
    nf = unicodedata.normalize("NFD", s)
    nf = nf.replace("đ", "d").replace("Đ", "D")
    return "".join(ch for ch in nf if not unicodedata.combining(ch))

def _basic_norm(s: str) -> str:
    s = _strip_accents(s or "").lower()
    s = re.sub(r"[^a-z0-9\s\-\+_/\.]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def _fuzzy_ratio(a: str, b: str) -> float:
    a = _basic_norm(a); b = _basic_norm(b)
    if not a and not b: return 100.0
    return 100.0 * difflib.SequenceMatcher(None, a, b).ratio()

def canon_tool_name(name: str) -> str:
    n = (name or "").strip()
    if not n: return ""
    low = _basic_norm(n)
    n2 = ALIAS_TO_CANON.get(low, n)
    return n2 if n2 in ALLOWED_TOOLS else (n if n in ALLOWED_TOOLS else "")

# ==== canon location helpers ====
def canon_location_from_string(s: str) -> Optional[str]:
    qn = _basic_norm(s)
    for k, v in LOC_SYNONYMS.items():
        if k in qn or qn == k:
            return v  # luôn trả về ASCII "Ho Chi Minh" | "Ha Noi" | "Da Nang"
    return None

def _ner_vi_locations(text: str) -> List[str]:
    if vn_ner is None or not isinstance(text, str):
        return []
    spans, buf = [], []
    try:
        for w, pos, chunk, tag in vn_ner(text):
            if isinstance(tag, str) and tag.startswith("B-LOC"):
                if buf: spans.append(" ".join(buf)); buf = []
                buf = [w]
            elif isinstance(tag, str) and tag.startswith("I-LOC"):
                if buf: buf.append(w)
            else:
                if buf: spans.append(" ".join(buf)); buf = []
        if buf: spans.append(" ".join(buf))
    except Exception:
        return []
    return spans

def _ner_en_locations(text: str) -> List[str]:
    if _SPACY_EN is None or not isinstance(text, str):
        return []
    try:
        doc = _SPACY_EN(text)
        return [ent.text for ent in doc.ents if ent.label_ in ("GPE", "LOC")]
    except Exception:
        return []

def canon_location_from_query_fallback(q: str) -> Optional[str]:
    qn = _basic_norm(q)
    for k, v in LOC_SYNONYMS.items():
        if k in qn:
            return v
    return None

def _strip_role_prefix(s: str) -> str:
    return re.compile(r'^\s*(?:user|assistant)\s*:\s*', re.I).sub('', s)

ROLE_PREFIX_RE = re.compile(r'^\s*(?:user|assistant)\s*:\s*', re.I)
LOC_PREFIX_RE  = re.compile(r'(?i)^\s*(in|ở|tai)\s+(ho chi minh|hồ chí minh|hcm|sg|saigon|ha noi|hà nội|hanoi|hn|da nang|đà nẵng|danang|dn)\s*,?\s*')
LOC_TAIL_RE    = re.compile(r'(?i)\s+(in|ở|tai)\s+(ho chi minh|hồ chí minh|hcm|sg|saigon|ha noi|hà nội|hanoi|hn|da nang|đà nẵng|danang|dn)\b.*$')
COMPARE_TAIL_RE= re.compile(r'(?i)\s+(vs|versus)\s+.*$')
TRAILERS_RE    = re.compile(r'(?i)\s+(price|prices|cost|stock|availability|specs?|specifications|reviews?|rating|today|with|for(\s+\w+)*|is in stock)\s*[\?\.\! ,;:]*$')

AND_SPLIT_RE   = re.compile(r'(?i)\s+(?:vs|versus|and|&|và|voi|with)\s+')

def _strip_location_tail(s: str) -> str:
    return LOC_TAIL_RE.sub('', s)

def _strip_compare_tail(s: str) -> str:
    return COMPARE_TAIL_RE.sub('', s)

def _strip_trailers(s: str) -> str:
    return TRAILERS_RE.sub('', s)

def _strip_role_loc(text: str) -> str:
    if not isinstance(text, str): return ""
    s = ROLE_PREFIX_RE.sub("", text)
    s = LOC_PREFIX_RE.sub("", s)
    s = LOC_TAIL_RE.sub("", s)
    s = s.strip(" ?.,!")
    return s

def canon_location_from_query(q: str) -> Optional[str]:
    raw, canon = (lambda x: detect_location_dual(x))(q)
    return canon if canon else None

def product_sanitize(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.strip()
    s = _strip_role_prefix(s)
    s = _strip_location_tail(s)
    s = _strip_compare_tail(s)
    s = _strip_trailers(s)
    s = re.sub(r'\s+', ' ', s)
    return s.strip()

def clean_surface_product(name: str) -> str:
    if not isinstance(name, str): return ""
    return product_sanitize(name)

# --- Args normalizer for schema compliance ---
POS_INT_RE = re.compile(r"^[1-9]\d*$")

def normalize_args_for_schema(raw_args: Dict[str, Any]) -> Dict[str, Any]:
    args = dict(raw_args) if isinstance(raw_args, dict) else {}

    # Map Total_product -> total_product
    if "Total_product" in args and "total_product" not in args:
        args["total_product"] = args.pop("Total_product")

    def _clean_list(lst):
        if not isinstance(lst, list):
            return []
        keep = []
        for p in lst:
            if isinstance(p, str):
                ps = product_sanitize(p)
                if ps:
                    keep.append(ps)
        return keep

    out: Dict[str, Any] = {}

    if "products" in args:
        prods = _clean_list(args.get("products"))
        if len(prods) >= 2:
            out = {"products": prods, "total_product": str(len(prods))}
        elif len(prods) == 1:
            out = {"product": prods[0], "total_product": "1"}
        else:
            out = {}
    elif "product" in args and isinstance(args["product"], str):
        prod = product_sanitize(args["product"])
        if prod:
            out = {"product": prod, "total_product": "1"}
        else:
            out = {}
    else:
        out = {}

    if "total_product" in out:
        tp = str(out["total_product"])
        if not POS_INT_RE.fullmatch(tp):
            if "products" in out:
                out["total_product"] = str(max(1, len(out["products"])))
            elif "product" in out:
                out["total_product"] = "1"
            else:
                out.pop("total_product", None)

    if "products" in out:
        out = {"products": out["products"], "total_product": out.get("total_product", str(len(out["products"])))}
    elif "product" in out:
        out = {"product": out["product"], "total_product": out.get("total_product", "1")}
    else:
        out = {}

    return out

# ---------- JSON extractor ----------
def extract_json_strict(text: str, begin="<<BEGIN_JSON>>", end="<<END_JSON>>") -> Optional[str]:
    if not isinstance(text, str): return None
    bi = text.rfind(begin)
    frag = text[bi+len(begin):] if bi != -1 else text
    ei = frag.find(end) if bi != -1 else -1
    if ei != -1: frag = frag[:ei]
    start = frag.find("{")
    if start == -1: return None
    buf = []; bal = 0; started = False
    for ch in frag[start:]:
        buf.append(ch)
        if ch == "{":
            bal += 1; started = True
        elif ch == "}":
            bal -= 1
            if started and bal == 0:
                s = "".join(buf)
                try:
                    json.loads(s)
                    return s
                except Exception:
                    return None
    return None

# ==== detect location kết hợp NER + regex + gazetteer ====
def detect_location_dual(q: str) -> Tuple[Optional[str], Optional[str]]:
    candidates: List[str] = []
    candidates += _ner_vi_locations(q)
    candidates += _ner_en_locations(q)
    m = re.search(r"(?i)\b(?:in|ở|tai|tại)\s+([A-Za-zÀ-ỹ0-9\-\s]+)", q)
    if m:
        candidates.append(m.group(1).strip(" ,.!?"))
    qn = _basic_norm(q)
    for k in LOC_SYNONYMS.keys():
        if k in qn:
            candidates.append(k)

    seen = set()
    for cand in candidates:
        ctext = cand.strip()
        if not ctext or ctext.lower() in seen:
            continue
        seen.add(ctext.lower())
        canon = canon_location_from_string(ctext)
        if canon:
            return ctext, canon

    if candidates:
        return candidates[0].strip(), None
    return None, None

# ---------- Stopping on token pattern ----------
class StopOnTokenPattern(StoppingCriteria):
    def __init__(self, tokenizer, pattern="<<END_JSON>>"):
        self.ids = tokenizer(pattern, add_special_tokens=False).input_ids
        self.k = len(self.ids)
    def __call__(self, input_ids, scores, **kwargs):
        seq = input_ids[0].tolist()
        return len(seq) >= self.k and seq[-self.k:] == self.ids

# ---------- NoBadWords helper ----------
def make_nbw_processor(tokenizer, bad_strings: List[str]):
    bad_ids = []
    for s in bad_strings:
        try:
            ids = tokenizer(s, add_special_tokens=False).input_ids
            if ids: bad_ids.append(ids)
        except Exception:
            pass
    from transformers.generation.logits_process import NoBadWordsLogitsProcessor
    try:
        return NoBadWordsLogitsProcessor(bad_words_ids=bad_ids, eos_token_id=tokenizer.eos_token_id)
    except TypeError:
        return NoBadWordsLogitsProcessor(bad_ids)

# ---------- Prompt builder ----------
def load_policy_text(policy_path: Path) -> str:
    if policy_path and policy_path.exists():
        return policy_path.read_text(encoding="utf-8")
    return ""

class PromptBuilderUploaded:
    def __init__(self, policy_path: Path):
        self.policy_machine = load_policy_text(policy_path)

    def build_inference_prompt(self, query: str) -> str:
        contract = (
            "Return exactly ONE JSON between <<BEGIN_JSON>> and <<END_JSON>>. "
            "No extra text before/after. Fields: reasoning|null; location∈{Ho Chi Minh, Ha Noi, Da Nang|null}; "
            "tool_sequence=[{tool∈{check_stock,check_price,policy_look_up_tool,check_spec,get_product_reviews,recommend_product,compare_all}, "
            "args=({product,total_product:\"1\"}|{products[],total_product})}]. "
            "Do NOT include location inside args. Keep product surface (trim only)."
        )
        return (
            "# POLICY (machine) — compact\n" + contract + "\n\n" +
            f"# USER QUERY\n{query}\n\n" +
            "<<BEGIN_JSON>>\n" +
            "{"
        )

# ---------- Model loader ----------
def load_tokenizer_and_model(base_model: str, ckpt_dir: Path, deterministic: bool = True):
    try:
        tok = AutoTokenizer.from_pretrained(str(ckpt_dir), use_fast=False, trust_remote_code=True)
    except Exception:
        tok = AutoTokenizer.from_pretrained(base_model, use_fast=False, trust_remote_code=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    compute_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    try:
        bnb_cfg = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                                     bnb_4bit_use_double_quant=True, bnb_4bit_compute_dtype=compute_dtype)
        base = AutoModelForCausalLM.from_pretrained(base_model, trust_remote_code=True,
                                                    quantization_config=bnb_cfg, device_map="auto")
    except Exception:
        base = AutoModelForCausalLM.from_pretrained(base_model, trust_remote_code=True)
        if torch.cuda.is_available(): base.to("cuda:0")

    model = PeftModel.from_pretrained(base, str(ckpt_dir))
    model.eval()

    if deterministic:
        torch.manual_seed(0)

    return tok, model

# === Cell 2: Evaluator (in-memory; không ghi file) ===
BAD_STRINGS = [
    "```","```json","```python",
    "Return ONLY ONE JSON object","Return exactly ONE JSON","# POLICY","# USER QUERY",
    "<<BEGIN_JSON>> and <<END_JSON>>","<<BEGIN_JSON>>",
    "import ","class ","def ","from ","open(","json.load(","json.dump(",
    "User:", "Assistant:", "user:", "assistant:"
]

class EvaluatorGuarded:
    def __init__(self, base_model: str, ckpt_dir: Path, policy_path: Path,
                 max_new_tokens: int = 160, use_outline: bool = True, deterministic: bool = True,
                 print_model_reasoning: bool = False):   # NEW
        self.base_model = base_model
        self.ckpt_dir   = Path(ckpt_dir)
        self.max_new_tokens = int(max_new_tokens)
        self.use_outline = bool(use_outline)
        self.print_model_reasoning = bool(print_model_reasoning)  # NEW

        self.tok, self.model = load_tokenizer_and_model(base_model, self.ckpt_dir, deterministic=deterministic)
        self.pb = PromptBuilderUploaded(policy_path)
        self._end_stopper = StoppingCriteriaList([StopOnTokenPattern(self.tok, "<<END_JSON>>")])

    @torch.no_grad()
    def _decode_guarded(self, prompt: str, max_new_tokens: Optional[int] = None) -> Tuple[Optional[str], str]:
        if max_new_tokens is None: max_new_tokens = self.max_new_tokens
        enc = self.tok(prompt, return_tensors="pt", truncation=True, max_length=1800).to(self.model.device)
        nbw = make_nbw_processor(self.tok, BAD_STRINGS)
        lp = LogitsProcessorList([nbw])
        out = self.model.generate(
            **enc,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            logits_processor=lp,
            stopping_criteria=self._end_stopper,
            pad_token_id=self.tok.pad_token_id,
            eos_token_id=self.tok.eos_token_id,
            use_cache=True
        )
        txt = self.tok.decode(out[0], skip_special_tokens=True)
        js_text = extract_json_strict(txt, begin="<<BEGIN_JSON>>", end="<<END_JSON>>")
        return js_text, txt

    def _intent_from_query(self, q: str) -> Dict[str, bool]:
        qn = _basic_norm(q)
        def has(keys): return any(k in qn for k in keys)
        return {
            "stock": has(INTENT_KEYWORDS["stock"]),
            "price": has(INTENT_KEYWORDS["price"]),
            "policy": has(INTENT_KEYWORDS["policy"]),
            "spec": has(INTENT_KEYWORDS["spec"]),
            "reviews": (has(INTENT_KEYWORDS["reviews"]) or has_reviews_intent(q)),
            "recommend": has(INTENT_KEYWORDS["recommend"]),
            "compare": has(INTENT_KEYWORDS["compare"]),
        }

    def _extract_product_from_query(self, query: str) -> Optional[str]:
        if not isinstance(query, str) or not query.strip():
            return None
        s = _strip_role_loc(query)
        s = _expand_phone_aliases(s)
        s = re.split(r'(?i)\b(?:vs|versus)\b', s)[0]
        s = re.sub(r'(?i)^\s*compare\s+', '', s)
        pat = r'(?i)(iphone|ipad|macbook|airpods|watch|galaxy|pixel|oneplus|oppo|reno|find|xiaomi|redmi|poco|realme|vivo|huawei|honor|asus|rog|nokia|tecno|infinix)\s+[A-Za-z0-9][A-Za-z0-9\s\-\+]*'
        m = re.search(pat, s, flags=re.I)
        return clean_surface_product(m.group(0)) if m else None

    def _extract_compare_products(self, query: str) -> List[str]:
        s = _strip_role_loc(query)
        s = _expand_phone_aliases(s)
        s = re.sub(r'(?i).*?\b(compare|so\s*s(á|a)nh)\b', '', s, count=1).strip() or s
        s = AND_SPLIT_RE.sub('|', s).strip(" ?.!")

        parts = [product_sanitize(p) for p in s.split('|')]
        parts = [p for p in parts if p]

        def _is_compare_like(p: str) -> bool:
            if not p: return False
            brand_pat = re.compile(
                r'(?i)\b('
                r'iphone|ipad|pad\s*air|ipad\s*air|ipad\s*mini|macbook|airpods|apple\s*watch|watch|'
                r'galaxy|pixel|oneplus|oppo|reno|find|xiaomi|redmi|poco|realme|vivo|huawei|honor|asus|rog|nokia|tecno|infinix'
                r')\b'
            )
            return bool(brand_pat.search(p))

        parts = [p for p in parts if _is_compare_like(p)]

        if len(parts) >= 2:
            uniq = []
            for p in parts:
                if p not in uniq:
                    uniq.append(p)
            return uniq[:2]
        return []

    def outline_skeleton(self, query: str) -> Dict[str, Any]:
        intents = self._intent_from_query(query)

        loc_raw, loc_canon = detect_location_dual(query)
        loc = loc_canon  # luôn ASCII hoặc None

        pair: List[str] = self._extract_compare_products(query) if intents["compare"] else []
        prod = self._extract_product_from_query(query)

        seq: List[Dict[str, Any]] = []
        def add(tool_name: str):
            t = canon_tool_name(tool_name)
            if not t: return
            step = {"tool": t, "args": {}}
            if len(pair) == 2 and t in {"check_stock","check_price","check_spec","policy_look_up_tool","get_product_reviews","recommend_product"}:
                step["args"]["products"] = pair
                step["args"]["total_product"] = "2"
            elif prod and t != "compare_all":
                step["args"]["product"] = prod
                step["args"]["total_product"] = "1"
            seq.append(step)

        if intents["stock"]: add("check_stock")
        if intents["price"]: add("check_price")
        if intents["policy"]: add("policy_look_up_tool")
        if intents["spec"]: add("check_spec")
        if intents["reviews"]: add("get_product_reviews")
        if intents["recommend"]: add("recommend_product")

        if intents["compare"] and len(pair) == 2 and not any(
            intents[k] for k in ["stock","price","policy","spec","reviews","recommend"]
        ):
            seq.append({"tool":"compare_all","args":{"products": pair, "total_product":"2"}})

        return {"reasoning": None, "location": (loc if loc else None), "tool_sequence": seq}

    # ---------- Coerce/Normalize + rescue ----------
    def coerce_to_schema(self, obj: Any) -> Dict[str, Any]:
        out: Dict[str, Any] = {"reasoning": None, "location": None, "tool_sequence": []}
        if isinstance(obj, dict):
            out["reasoning"] = None if obj.get("reasoning") is None else str(obj.get("reasoning"))
            out["location"] = obj.get("location", None)
            seq = obj.get("tool_sequence", [])
            if not isinstance(seq, list): seq = [] if seq is None else [seq]
            for step in seq:
                if isinstance(step, dict):
                    out["tool_sequence"].append({
                        "tool": (step.get("tool") or step.get("name") or ""),
                        "args": (step.get("args") or {}) if isinstance(step.get("args"), dict) else {}
                    })
        return out

    def normalize_and_validate(self, record: Dict[str, Any], query: str) -> Tuple[Dict[str, Any], Dict[str, Any]]:
        notes = {"dropped_steps": [], "fixed_steps": [], "order": "reordered_by_priority"}
        r = json.loads(json.dumps(record, ensure_ascii=False))

        # short-circuit nếu phát hiện địa danh nhưng không hỗ trợ
        raw_loc, canon_loc = detect_location_dual(query)
        if raw_loc and not canon_loc:
            unsupported = {"reasoning": f"Không hỗ trợ tại {raw_loc[:60]}", "location": None, "tool_sequence": []}
            validate_or_raise(unsupported)
            return unsupported, {"short_circuit": "unsupported_location", "raw_location": raw_loc}

        # nếu có canon_loc, set location; không thì None
        r["location"] = canon_loc if canon_loc else None  # luôn là ASCII hoặc None

        seq_in = r.get("tool_sequence") or []
        bucket = {}
        for st in seq_in:
            raw_tool = st.get("tool","")
            t = canon_tool_name(raw_tool)
            if not t:
                notes["dropped_steps"].append({"tool_raw": raw_tool, "reason":"unknown_or_disallowed"})
                continue
            args = st.get("args") or {}

            if "products" in args and "product" in args:
                args.pop("product", None)
            if "product" in args:
                args["product"] = product_sanitize(args["product"])
                args["total_product"] = "1"
            elif "products" in args and isinstance(args["products"], list):
                args["products"] = [product_sanitize(p) for p in args["products"] if isinstance(p,str) and product_sanitize(p)]
                if not args["products"]:
                    notes["dropped_steps"].append({"tool": t, "reason":"empty_products"})
                    continue
                args["total_product"] = str(len(args["products"]))
            else:
                if t != "compare_all":
                    prod2 = self._extract_product_from_query(query)
                    if prod2:
                        args = {"product": prod2, "total_product":"1"}
                    else:
                        args = {}

            if t == "compare_all":
                prods_in = args.get("products", [])
                fixed = []
                for p in prods_in:
                    if AND_SPLIT_RE.search(p):
                        parts = [product_sanitize(x) for x in AND_SPLIT_RE.split(p)]
                        fixed.extend([pp for pp in parts if pp])
                    else:
                        fixed.append(product_sanitize(p))
                fixed = [p for p in fixed if p and p.lower() not in ("user", "assistant")]
                uniq = []
                for p in fixed:
                    if p not in uniq:
                        uniq.append(p)
                if len(uniq) >= 2:
                    args["products"] = uniq[:2]
                    args["total_product"] = "2"
                else:
                    notes["dropped_steps"].append({"tool":"compare_all","reason":"need_two_products_after_sanitize"})
                    continue

                args = normalize_args_for_schema(args)
            else:
                args = normalize_args_for_schema(args)

            key = t
            if key not in bucket:
                bucket[key] = {"tool": t, "args": args}
            else:
                prev = bucket[key]["args"]
                score = lambda a: int(bool(a.get("product"))) + int(bool(a.get("products"))) + int(bool(a.get("total_product")))
                if score(args) > score(prev):
                    bucket[key]["args"] = args

        intents_check = self._intent_from_query(query)
        if intents_check["reviews"] and "get_product_reviews" not in bucket:
            prod3 = self._extract_product_from_query(query)
            bucket["get_product_reviews"] = {"tool":"get_product_reviews","args":({"product": prod3, "total_product":"1"} if prod3 else {})}
            notes.setdefault("rescued", []).append("get_product_reviews")

        ordered = [bucket[t] for t in TOOL_PRIORITY if t in bucket]
        r["tool_sequence"] = ordered
        notes["fixed_steps"] = ordered
        return r, notes

    # ---------- Pipeline ----------
    @torch.no_grad()
    def debug_pipeline(self, query: str) -> Dict[str, Any]:
        prompt = self.pb.build_inference_prompt(query)
        js_text, raw = self._decode_guarded(prompt, max_new_tokens=self.max_new_tokens)

        raw_reasoning = None  # NEW: giữ reasoning gốc
        obj_model = {}
        if js_text is not None:
            try:
                _raw_obj = json.loads(js_text)
                raw_reasoning = _raw_obj.get("reasoning", None)
            except Exception:
                pass
            try:
                obj_model = json.loads(js_text)
            except Exception:
                obj_model = {}
        obj_model = self.coerce_to_schema(obj_model)

        skel = self.outline_skeleton(query) if self.use_outline else {"reasoning": None, "location": None, "tool_sequence": []}

        seq_model = obj_model.get("tool_sequence") or []
        seq_skel  = skel.get("tool_sequence") or []
        merged = []
        seen = set()
        def score(a):
            if not isinstance(a, dict): return -1
            args = a.get("args",{}) or {}
            return int(bool(args.get("product"))) + int(bool(args.get("products"))) + int(bool(args.get("total_product")))
        for cand in seq_model + seq_skel:
            t = canon_tool_name((cand or {}).get("tool",""))
            if not t: continue
            if t not in seen:
                merged.append(cand); seen.add(t)
            else:
                for i, s in enumerate(merged):
                    if canon_tool_name(s.get("tool","")) == t and score(cand) > score(s):
                        merged[i] = cand
                        break

        obj_merged = {"reasoning": None, "location": obj_model.get("location") or skel.get("location"), "tool_sequence": merged}
        final, notes = self.normalize_and_validate(obj_merged, query)

        try:
            validate_or_raise(final)
        except Exception:
            fallback, _ = self.normalize_and_validate(skel, query)
            validate_or_raise(fallback)
            final = fallback

        return {
            "query": query,
            "decoder_used": "GUARDED_GENERATE",
            "raw_tail": (raw[-RAW_TAIL_CHARS:] if isinstance(raw, str) else ""),
            "pred_before_norm": obj_model,
            "skeleton": skel,
            "merged": obj_merged,
            "final": final,
            "notes": notes,
            "model_reasoning": raw_reasoning  # NEW
        }

    # ---------- Helper: chỉ lấy reasoning phần gen ----------
    def get_model_reasoning_only(self, query: str) -> Optional[str]:  # NEW
        info = self.debug_pipeline(query)
        return info.get("model_reasoning")

    # ---------- In-memory run ----------
    def run_on_records(self, inputs: List[Dict[str, Any]], gts: Optional[List[Dict[str, Any]]] = None,
                       print_first: int = 6) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
        def unwrap(y):
            return y["output"] if (isinstance(y, dict) and "output" in y and isinstance(y["output"], dict)) else y

        results, tool_hist_pred, tool_hist_gt = [], {}, {}
        t0 = time.time()
        reviews_miss = []

        for i, x in enumerate(inputs):
            q = (x or {}).get("query","")
            info = self.debug_pipeline(q)
            pred = info["final"]

            rec_row = {
                "query": q,
                "pred": pred,
                "decoder": info["decoder_used"],
                "raw_tail": info["raw_tail"],
                "notes": info["notes"],
                "pred_before_norm": info["pred_before_norm"],
                "skeleton": info["skeleton"],
                "merged": info["merged"],
                "model_reasoning": info.get("model_reasoning")  # NEW
            }

            if gts is not None:
                y = unwrap(gts[i]) if i < len(gts) else {}
                gt = self.coerce_to_schema(y or {})
                gt["location"] = canon_location_from_query(q) if canon_location_from_query(q) else None

                em_strict = (json.dumps(pred, ensure_ascii=False, sort_keys=True) ==
                             json.dumps(gt,   ensure_ascii=False, sort_keys=True))
                def tool_names(obj):
                    seq = (obj or {}).get("tool_sequence") or []
                    return [canon_tool_name(s.get("tool")) for s in seq if isinstance(s, dict) and canon_tool_name(s.get("tool"))]
                same_loc = (pred or {}).get("location", None) == (gt or {}).get("location", None)
                em_logic = same_loc and (tool_names(pred) == tool_names(gt))

                ps, gs = set(tool_names(pred)), set(tool_names(gt))
                tp = len(ps & gs); fp = len(ps - gs); fn = len(gs - ps)
                prec = tp / (tp+fp) if (tp+fp)>0 else 0.0
                rec  = tp / (tp+fn) if (tp+fn)>0 else 0.0
                f1   = 2*prec*rec/(prec+rec) if (prec+rec)>0 else 0.0

                for t in tool_names(pred): tool_hist_pred[t] = tool_hist_pred.get(t,0)+1
                for t in tool_names(gt):   tool_hist_gt[t]   = tool_hist_gt.get(t,0)+1

                gt_tools = set(tool_names(gt))
                pd_tools = set(tool_names(pred))
                if "get_product_reviews" in gt_tools and "get_product_reviews" not in pd_tools:
                    intents = self._intent_from_query(q)
                    reviews_miss.append({
                        "idx": i, "query": q,
                        "intent_detected_reviews": intents["reviews"],
                        "gt_has_reviews": True, "pred_has_reviews": False
                    })

                rec_row.update({
                    "gt": gt,
                    "exact_match_strict": bool(em_strict),
                    "exact_match_logic": bool(em_logic),
                    "tool_set_scores": {"precision": prec, "recall": rec, "f1": f1},
                })

            results.append(rec_row)

            if i < int(print_first):
                print("\n" + "="*90)
                print(f"[{i}] query:", q)
                if self.print_model_reasoning:
                    print("- model_reasoning:", json.dumps(rec_row["model_reasoning"], ensure_ascii=False))  # NEW
                print("- pred(final):", json.dumps(pred, ensure_ascii=False))

        elapsed = time.time() - t0

        if gts is None:
            metrics = {
                "total": len(results),
                "elapsed_sec": elapsed,
                "tools_pred_hist": tool_hist_pred,
                "note": "No ground-truth provided → metrics vs GT not computed."
            }
        else:
            em_logic_rate = float(sum(r.get("exact_match_logic", False) for r in results)) / max(len(results),1)
            em_strict_rate = float(sum(r.get("exact_match_strict", False) for r in results)) / max(len(results),1)
            f1s = [r["tool_set_scores"]["f1"] for r in results]
            precs = [r["tool_set_scores"]["precision"] for r in results]
            recs  = [r["tool_set_scores"]["recall"] for r in results]
            metrics = {
                "total": len(results),
                "em_strict_rate": em_strict_rate,
                "em_logic_rate": em_logic_rate,
                "tool_set_precision_avg": float(np.mean(precs)) if precs else 0.0,
                "tool_set_recall_avg": float(np.mean(recs)) if recs else 0.0,
                "tool_set_f1_avg": float(np.mean(f1s)) if f1s else 0.0,
                "tools_pred": tool_hist_pred,
                "tools_gt": tool_hist_gt,
                "elapsed_sec": elapsed,
                "reviews_miss_count": len(reviews_miss)
            }

        return results, metrics

# === Cell 3: Runner — chỉ xử lí trực tiếp, không ghi file ===
def run_eval_direct(base_model: str,
                    ckpt_dir: str,
                    policy_path: str = "",
                    queries: List[str] = None,
                    print_first: int = PRINT_FIRST,
                    max_new_tokens: int = MAX_NEW_TOKENS,
                    use_outline: bool = USE_OUTLINE,
                    deterministic: bool = DETERMINISTIC,
                    gts: Optional[List[Dict[str, Any]]] = None
                   ) -> Tuple[List[Dict[str, Any]], Dict[str, Any], List[Dict[str, Any]]]:
    """
    Trả về:
      - final_pred: list JSON hợp lệ theo schema của bạn
      - metrics: dict (nếu không có GT thì chỉ có tổng quan)
      - debug_rows: list chi tiết từng mẫu (raw_tail, skeleton, merged, notes)
    """
    if queries is None:
        queries = []

    ev = EvaluatorGuarded(
        base_model=base_model,
        ckpt_dir=Path(ckpt_dir),
        policy_path=Path(policy_path) if policy_path else Path(),
        max_new_tokens=max_new_tokens,
        use_outline=use_outline,
        deterministic=deterministic
    )

    inputs = [{"query": q} for q in queries]
    rows, metrics = ev.run_on_records(inputs, gts=gts, print_first=print_first)
    final_pred = [r["pred"] for r in rows]
    return final_pred, metrics, rows

# ====== Ví dụ chạy nhanh (chỉ cần đặt BASE_MODEL/CKPT_DIR/QUERIES) ======
# Lưu ý:
# - Nếu không có internet, BASE_MODEL phải trỏ tới thư mục local chứa config.json, tokenizer_config.json, trọng số,...
# - CKPT_DIR là thư mục LoRA đã upload (adapter_config.json + adapter_model.*)
try:
    QUERIES = [
        "Giá iPhone 15 Pro ở QN",
        "So sánh Galaxy S23 Ultra vs iPhone 14 Pro in đà nẵng",
        "ip 17 plus price"
    ]
    final_pred, metrics, debug_rows = run_eval_direct(
        base_model=BASE_MODEL,
        ckpt_dir=str(CKPT_DIR),
        policy_path=str(POLICY_PATH),
        queries=QUERIES,
        print_first=3,
        max_new_tokens=160
    )
    print("\n[FINAL_PRED] samples:", len(final_pred))
    print(json.dumps(final_pred[:3], ensure_ascii=False, indent=2))
    print("\n[METRICS]")
    # sau khi có `metrics`:
    metrics = {k: v for k, v in metrics.items() if k not in ("tools_pred_hist", "note")}
    print(json.dumps(metrics, ensure_ascii=False, indent=2))
except Exception as e:
    print("Runtime error:", repr(e))



